name: Publish to GitHub Packages

on:
  push:
    branches:
      - main   # or master

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          scope: '@Aneeshpissay330'

      - run: npm install
      - run: npm run build
      - run: npm version patch -m "ci: bump version to %s"   # bump version automatically
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
